
export IMAGE_NAME="elasticsearch"
export IMAGE_VERSION="8.11.4"

docker pull $IMAGE_NAME:$IMAGE_VERSION
docker tag $IMAGE_NAME:$IMAGE_VERSION $HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:$IMAGE_VERSION
docker push $HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:$IMAGE_VERSION

export IMAGE_NAME="kibana"
export IMAGE_VERSION="8.11.4"

docker pull $IMAGE_NAME:$IMAGE_VERSION
docker tag $IMAGE_NAME:$IMAGE_VERSION $HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:$IMAGE_VERSION
docker push $HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:$IMAGE_VERSION

export IMAGE_NAME="busybox"
export IMAGE_VERSION="latest"

docker pull $IMAGE_NAME:$IMAGE_VERSION
docker tag $IMAGE_NAME:$IMAGE_VERSION $HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:$IMAGE_VERSION
docker push $HARBOR_URL/$HARBOR_PROJECT/$IMAGE_NAME:$IMAGE_VERSION
