projects:
- name: tack-1
  description: This is Project 1
  users:
    - user: fop-platform-admin@example.com
      roleSetRef: roleSets/developer
- name: tack-2
  description: This is Project 2
  users:
    - user: fop-platform-admin@example.com
      roleSetRef: roleSets/developer
roleSets:
  developer:
    roles:
      - project-iam-admin
      - k8s-networkpolicy-admin
