apiVersion: v1
kind: Service
metadata:
  name: ollama-service
  namespace: ${NAMESPACE}
spec:
  type: LoadBalancer 
  selector:
    app: ollama
  ports:
  - protocol: TCP
    port: 11434
    targetPort: 11434